### ISSUE TITLE
Reference instead of a node name in status output

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppetlabs-catalog_preview#158]
`
 # puppet preview --pe development --be testing node.example.com --view status --last
`

`
Catalogs for node '#<PuppetX::Puppetlabs::Migration::OverviewModel::Query::Wrapper:0x00000003ad0720>' are equal.
`

**Comment by HAIL9000** [comment]
Hey again! This is now captured in [PRE-135](https://tickets.puppetlabs.com/browse/PRE-135).
