### ISSUE TITLE
Change the word 'conflict'(s) to 'difference'(s)

### ISSUE THREAD

**Issue by natemccurdy** [puppetlabs/puppetlabs-catalog_preview#162]
The word `conflict` is a bit ambiguos to me. What that's showing is that there is a difference in a resource in the catalog. So, I propose that we change the word to `difference` in the output of the preview tool.

**Comment by HAIL9000** [comment]
Hey thank you for reporting this! For the sake of keeping everything in one place we're going to be disabling GitHub issues for this project so I have migrated your issue to Jira ticket [PRE-134](https://tickets.puppetlabs.com/browse/PRE-134). Please direct further comments/questions over there.

Thank you!
