### ISSUE TITLE
Compare catalogs from 2 puppet masters

### ISSUE THREAD

**Issue by vinzent** [puppetlabs/puppetlabs-catalog_preview#183]
Before upgrading the Puppet master server I'd like to spin up the new Puppet master on a test VM and  compare catalogs against the production Puppet master to become confident that no unexpected changes happen.

The `baseline-environment` and `preview-environment`parameters could be expanded to include a server like `(<server>(:<port>)?/)?<environment>` and then call the catalog compilation by the catalog rest indirector. This would require adding permissions `auth.conf` on `<server>`

Another possibility would be to have a two phased preview: 
- first run catalog baseline compilation on the production master
- transfer baseline catalogs to test puppet master and then 
- run only preview compilation and compare them.

**Comment by HAIL9000** [comment]
Hey thank you for reporting this! For the sake of keeping everything in one place we're going to be disabling GitHub issues for this project so I have migrated your issue to Jira ticket [PRE-133](https://tickets.puppetlabs.com/browse/PRE-133). Please direct further comments/questions over there.

Thank you!
