### ISSUE TITLE
move documentation out of /lib

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppetlabs-catalog_preview#185]
since /lib folder is getting synced to all agents it would probably better to move all documentation into docs folder. 

The reason it came to my attention, on Solaris 10 plugin sync fails:

`Error: invalid byte sequence in US-ASCII
Error: /File[/opt/puppetlabs/puppet/cache/lib/puppet_x/puppetlabs/preview/api/documentation/preview-help.md]/content: change from {md5}84f5f1f9dd1b9e6ac8926af476ee4999 to {md5}e9c12f4d53774a330822e5cf6c27797c failed: invalid byte sequence in US-ASCII
`

**Comment by HAIL9000** [comment]
Hey again! As with #187 I've migrated this to Jira ticket [PRE-132](https://tickets.puppetlabs.com/browse/PRE-132).
