### ISSUE TITLE
status view incorrectly shows warnings as 

### ISSUE THREAD

**Issue by vchepkov** [puppetlabs/puppetlabs-catalog_preview#187]
I have some weird warning for each node in PE

```
Preview Warnings (by message)
  Class 'settings' is already defined; cannot redefine at : (202)
```

I wasn't able to find this class anywhere, unfortunately, must be in some ruby code.
But what's interesting, preview doesn't report it correctly either:

```
Summary:
  Total Number of Nodes...: 205
  Baseline Failed.........: 2
  Preview Failed..........: 0
  Catalogs with Difference: 203
  Compliant Catalogs......: 0
  Equal Catalogs..........: 200

```

Clearly, math doesn't adds up

**Comment by HAIL9000** [comment]
Hey thank you for reporting this! For the sake of keeping everything in one place we're going to be disabling GitHub issues for this project so I have migrated your issue to Jira ticket [PRE-131](PRE-131). Please direct further comments/questions over there.

Thank you!
