### ISSUE TITLE
output is hard to understand

### ISSUE THREAD

**Issue by GeoffWilliams** [puppetlabs/puppetlabs-catalog_preview#63]
## Scenario
I was able to run the `puppet preview` on a puppet master I have for my home network and I don't understand the output.

I have all code for all systems in an environment called `production` which is setup for the _old_ parser.  I'm running PE 3.8.0 with R10K but no customisations beyond this

## Trial run
I tried running:
```
root@puppet:/home/geoff# puppet preview --preview_environment production lsdserver.lan.asio
```

And I get:
```
ERROR: The ntp module is not supported on an  based system. at /etc/puppetlabs/puppet/environments/production/modules/ntp/manifests/params.pp:142 on node lsdserver.lan.asio
ERROR: The ntp module is not supported on an  based system. at /etc/puppetlabs/puppet/environments/production/modules/ntp/manifests/params.pp:142 on node lsdserver.lan.asio
Run 'puppet preview lsdserver.lan.asio --last --view baseline_log' for full details
Error: Error while compiling the baseline catalog

Summary:
  Total Number of Nodes...: 1
  Baseline Failed.........: 1
  Preview Failed..........: 0
  Catalogs with Difference: 0
  Compliant Catalogs......: 0
  Equal Catalogs..........: 0

baseline failed ([]): lsdserver.lan.asio
```
It looks like something is failing due to variable interpolation in the message about the ntp module (which is puppetlabs-ntp (v3.0.3)).

Looking at the run output I'm not sure if:
* I have set things up wrong
* there was an error running the preview command
* I have found a real error

Investigating the log as suggested is not helpful:
```
root@puppet:/home/geoff# puppet preview lsdserver.lan.asio --last --view baseline_log
[
  {
    "level": "err",
    "message": "The ntp module is not supported on an  based system. at /etc/puppetlabs/puppet/environments/production/modules/ntp/manifests/params.pp:142 on node lsdserver.lan.asio",
    "source": "Puppet",
    "tags": [
      "err"
    ],
    "time": "2015-06-10T14:08:55.251579166+10:00"
  },
  {
    "level": "err",
    "message": "The ntp module is not supported on an  based system. at /etc/puppetlabs/puppet/environments/production/modules/ntp/manifests/params.pp:142 on node lsdserver.lan.asio",
    "source": "Puppet",
    "tags": [
      "err"
    ],
    "time": "2015-06-10T14:08:55.251858941+10:00"
  }
]
```

**Comment by ahpook** [comment]
I got a similar problem when preview didn't get a valid factset for nodes; the errors are from weird things in catalog compilation that would never happen on a real node. I filed https://tickets.puppetlabs.com/browse/PRE-100 to track this, let's move the discussion there.
