### ISSUE TITLE
zero-to-hero instructions in the documentation would be a great improvment

### ISSUE THREAD

**Issue by GeoffWilliams** [puppetlabs/puppetlabs-catalog_preview#67]
At the moment users have to work through several sections to figure out how to setup systems and use the tool.

It would be great if there was a section outlining how to go from a freshly installed puppet system to one that is able to use the tool

**Comment by ahpook** [comment]
Totally agree with this @GeoffWilliams -- i'm working on some end-to-end docs that should address this.

**Comment by HAIL9000** [comment]
This issue has been migrated to [PRE-137](https://tickets.puppetlabs.com/browse/PRE-137).
