### ISSUE TITLE
[enhancement] report deprecated platforms to user

### ISSUE THREAD

**Issue by GeoffWilliams** [puppetlabs/puppetlabs-catalog_preview#70]
I run my Puppet Master on Debian and since this module is PE only, perhaps it would be good if the tool advises that this platform is no longer supported for the next version of PE and possibly advise users of their migration options

**Comment by hlindberg** [comment]
Not sure how that would be detected though - at best it could warn that you are running catalog preview on a platform that will no longer be supported.

**Comment by HAIL9000** [comment]
This issue has been migrated to [PRE-136](https://tickets.puppetlabs.com/browse/PRE-136).
